[package]
name = "day06"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
aoc_tools = { version = "0.1.0", path = "../aoc_tools" }
itertools = "0.13.0"
ndarray = "0.16.1"
rayon = "1.10.0"
