[package]
name = "day24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
aoc_tools = { version = "0.1.0", path = "../aoc_tools" }
itertools = "0.13.0"
regex = "1.11.1"
rstest = "0.23.0"
